## Options needed
# Finetuning style/ architecture: via downstream task (replicate CrisisBERT), via MLM, via Adapter
# Datasets
# Loss function
# Pre-trained model from huggingface
# Language

data_path: data/data/all_data_en/
task: informativeness # informativeness or humanitarian