name: "bertweet"
pretrained_model: "vinai/bertweet-base"
  #/export/home/kraft/infhome/CrisisLM/outputs/2022-03-03/19-52-08/tmp/checkpoint-20000

learning_rate: 1e-5 # 1e-4
adam_beta1: 0.9
adam_beta2: 0.999
weight_decay: 0.01
warmup_steps: 10000
num_train_epochs: 150
pad_to_max_length: True
max_seq_length: None
mlm_probability: 0.15
uniform_masking: True
per_device_train_batch_size: 64
per_device_eval_batch_size: 64