name: "train"

do_train: True
do_eval: True
continue_training: False

per_device_train_batch_size: 8
per_device_eval_batch_size: 8
learning_rate: 5e-5
weight_decay: 0
num_train_epochs: 1
pad_to_max_length: False
max_seq_length: None
mlm_probability: None

evaluation_strategy: "steps"
eval_steps: 500
logging_steps: 500
early_stopping: False
patience: 20

save_model: True