name: "train"

do_train: True
do_eval: True
continue_training: False

per_device_train_batch_size: 32
per_device_eval_batch_size: 32
learning_rate: 3e-5
weight_decay: 0.1
num_train_epochs: 60
pad_to_max_length: False
max_seq_length: None
mlm_probability: 0.15

evaluation_strategy: "steps"
eval_steps: 500
logging_steps: 5000
early_stopping: True
patience: 50

save_model: True
